### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by luigigf49** [uniface/Development-Tooling#3]
Sorry,

I have only found VersionControl9702.zip in Development-Tooling/uniface-version-control/Downloads/ and this zip file contains no folders and only two UAR.
Where am I doing wrong ?

Many thanks
Luigi

**Comment by uf-dakerman** [comment]
If you're trying to configure the version control tool for usage with your own project, please download the latest 9.7.03 version I have uploaded and follow the readme: https://github.com/uniface/Development-Tooling/blob/master/uniface-version-control/README.md to configure in your project. Please let us know if this works for you.

Regards,
David

**Comment by luigigf49** [comment]
Ok.

Many thanks.
