### ISSUE TITLE
Missing include module

### ISSUE THREAD

**Issue by GianniSandy** [uniface/Development-Tooling#4]
While compiling I got message:
(LPMX)  warning:   1000 - (Preprocessor) #INCLUDE 'VUT:IP_TEST_HELPERS' Not Found
 warning:   1000 - Module 'LPIMPORTUNIFACEEXPORT' not found.

I've searched for module IP_TEST_HELPERS but was not able to find it.

**Comment by diseli-uniface** [comment]
The mentioned include Proc and the components that refer to it are not part of the Meta Tools and have been removed now.
