### ISSUE TITLE
Signature Wizard

### ISSUE THREAD

**Issue by GianniSandy** [uniface/Development-Tooling#6]
Documentation and software include a "Signature Wizard" application; documentation reports it as:
********** ********** ********** **********
SigWiz is a Uniface support utility providing features not yet within the standard Uniface IDE. It's primary focus is the discovery, manipulation, and validation of Uniface signatures relating to COM and 3GL interface. Due to the diverse options interfacing to these non-uniface technologies it can be confusing decoding calls and parameter types.
********** ********** ********** **********
Unfortunately some signatures are missing while executing sigwiz application; these instructions do NOT succeed:
newinstance "YRTL", HYRTL 
newinstance "USER32", HUSER32
Could someone please answer to the following questions? Thanks.
- Is this SigWiz application expecting to work?
- If Yes, could YRTL and USER32 signatures be published?
- Could SigWiz documentation being completed?

Thanks!

**Comment by hollerith** [comment]
You can create signatures within the UDE not using this sigwiz application (I am not familiar with it so I have no idea whether it is working or not). You should not need signatures for YRTL unless you are calling exported functions yourself and even then it might be easier to use 'perform' .  Sorry I saw this and thought you'd be waiting a long time for a bump... what version of uniface are you using - latest?

**Comment by diseli-uniface** [comment]
The original project was created as a stand-alone project on BitBucket. But it seems that when it was moved to GitHub and included into the Development-Tooling project some files went missing. Sorry.

The project should now work again when using the Project Setup Tool.
