### ISSUE TITLE
Git versioning

### ISSUE THREAD

**Issue by MaxChaza** [uniface/Development-Tooling#8]
Hello,
what is the most advanced solution for using GIT to manage the versioning of a tool developed with Uniface?
Thank you in advance. 
Best regards

**Comment by uf-jhuggins** [comment]
Hi,

Please see: https://github.com/uniface/WASListener

Also, march-hare.com offer a commercial solution.

Regards,

Jason.

**Comment by MaxChaza** [comment]
Hi, 
Thanks Jason I will try WASListener
